@echo off
echo Parando containers e limpando volumes antigos...
cd /d "%~dp0template\backend"
docker compose down -v --remove-orphans
echo Forcando rebuild sem cache da imagem...
docker compose build --no-cache
echo Subindo containers...
docker compose up -d
echo Aguardando API e banco inicializarem (90s)...
timeout /t 90 /nobreak
echo Executando testes...
cd /d "%~dp0"
powershell -ExecutionPolicy Bypass -File "%~dp0test-api.ps1" > "%~dp0test-results.txt" 2>&1
echo Concluido! Ver test-results.txt
